language: python
dist: xenial
install:
  - sudo apt-get update --quiet --quiet
  - sudo apt-get install tox --yes
script:
  - make test
matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
  allow_failures:
    - python: 3.8-dev
